05 - HW - Знакомство с облачной инфраструктурой и облачными сервисами
Otus-DevOps-22-08/morf100s_infra pull request #2
Opened 2022-10-06 10:10 UTC by morf100s

Добавлена страница вики, с описанием решения для bastion хоста.
 - Подключение по ssh с прозрачным проксирование через bastion как jumphost
 - Реквизиты подключения по VPN к bastion
 - Описание технологий и ссылка на документацию OpenSSH

2022-10-06 14:26 UTC, mrgreyves requested changes
Здравствуйте!)
У вас не тестов
![image](https://user-images.githubusercontent.com/34331259/194338868-1094b476-3687-4225-b77b-c935fd2a7991.png)
При этом тесты есть в ветке play-travis
Вам нужно смержить ветку play-travis в main и затем подмержить main ветку в ветку текущего дз
ДЗ возвращаю на доработку

2022-10-07 07:21 UTC, mrgreyves requested changes
Здравствуйте!)
Тесты снова нужно добавить

2022-10-09 10:17 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Все выполнено корректно
Перед мержем просто добавьте пустую строчку в ридми, наведем немного красоты =)

2022-10-09 15:37 UTC, morf100s commented
@mrgreyves То есть, сделать еще один коммит в ветке cloud-bastion, в котором в файле README.md будет пустая строка в начале файла?

2022-10-14 12:43 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, еще один коммит нужно сделать в ветку cloud-bastion =)

2022-10-29 08:32 UTC, merged