Packer base
Otus-DevOps-22-08/morf100s_infra pull request #4
Opened 2022-11-20 09:07 UTC by morf100s

# Выполнено ДЗ № 07

 - [v ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Запустить команду `packer build -var-file=variables.json ubuntu16.json` в директории `packer`. предварительно сформировав используемые файлы. После старта ВМ, подключится к ней по SSH и 
 - Установите reddit:
```
sudo apt-get update
sudo apt-get install -y git
git clone -b monolith https://github.com/express42/reddit.git
cd reddit && bundle install
puma -d
```
## Как проверить работоспособность:
 - Перейти по ссылке откройте в браузере http://<внешний IP машины>:9292:

## PR checklist
 - [v ] Выставил label с номером домашнего задания
 - [v] Выставил label с темой домашнего задания

2022-11-20 17:25 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно добавить файл variables.json.example
Приключение на 10 минут
Так же не забудьте добавить фейковый ключик для доступа к облаку =)

2022-11-27 16:18 UTC, morf100s commented
Добавил

2022-11-28 19:50 UTC, mrgreyves requested changes
Здравствуйте!)
Переименуйте variables.json.examples в variables.json.example =)

2022-12-02 15:58 UTC, morf100s commented
> Здравствуйте!) Переименуйте variables.json.examples в variables.json.example =)

Сделано.

2022-12-04 14:12 UTC, mrgreyves approved these changes
Здравствуйте!)
Проверил ваше дз
Перед мержем добавьте фейковый ключик для пакера, что бы тесты стали целиком зеленые
ДЗ принимаю =)

2022-12-04 15:03 UTC, closed without merging