09 - HW - Принципы организации инфраструктурного кода и работа над ин…
Otus-DevOps-22-08/morf100s_infra pull request #6
Opened 2023-01-15 12:09 UTC by morf100s

# Выполнено ДЗ № 09

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Создан файл с s3 бэкендом для terraform
 - Файлы terraform разделены на стэйджи
 - Общий для стэйджей код вынесен в модули
 - Добавлено описание в файл README

## Как запустить проект:
 - В каталогах prod или stage запустить команду инициализации `terraform init`
 - В необходимом стэйдже запустить команду `terraform apply -auto-approve`

## Как проверить работоспособность:
 - После раскатывания terraform файлом будем выведены ip адреса ресурсов, к ним можно подключится по ssh.

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-01-17 12:19 UTC, mrgreyves requested changes
Здравствуйте!)
К сожалению у вас достаточно много ошибок
Нужно свериться с результатами тестов и поправить их
ДЗ возвращаю на доработку

2023-01-18 03:47 UTC, morf100s commented
Насколько я вижу, у Вас присутствуют ошибки в автотестах.
1. Недоспутимый ключ для команды `terraform validate`. Ключ `-var-file` явно относится к packer-у, поправите меня или тест))
```
     ×  Command: `cd terraform && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example` stdout should match "Terraform has been successfully initialized!"
```

2. В методичке по ДЗ, стоит четкое указание "Описание бекенда нужно вынести в отдельный файл backend.tf". У меня отдельный файл `backend.tf.example`. 
Да, про суффикса .example в задании ни слова, но в тестах у Вас идет проверка наличия совершенно другова файла:
```
     ×  File terraform/storage-bucket.tf should exist
```
Прокомментируйте, пожалуйста, 
 - почему в методичке стоит название `backend.tf`, а в тестах `storage-bucket.tf`
 - нужен ли суффикс в этом файле

Соотвественно, исправьте, пожалуйста, меточку или тесты.

3. В тестах идет проверка на наличие файлов terraform.tfvars.example в каталогах `terraform/prod` и `terraform/stage`, в методичке есть расплывчатое указание "В файлах terraform.tfvars.example ...", но нету информации об их нахождении, узнаю это из тестов. Пожалуйста, скорректируйте методичку ДЗ.

4. Неинформативная ошибка `+On ../modules/app/main.tf line 3: Unsuitable value: string required`, файл main.tf создан в соответствии с официальной документацией https://registry.terraform.io/providers/yandex-cloud/yandex/latest, третья строка это `    yandex = {`, она скопирована с оф.документации. Прокомментируйте ошибку, что не так?

2023-01-23 16:51 UTC, morf100s commented
@mrgreyves Скажите, пожалуйста, когда будут исправлены тесты или будут конструктивные комментарии?

2023-01-25 13:46 UTC, mrgreyves approved these changes
Здравствуйте!)
Это тоже можно мержить, будьте внимательны с мерж конфликтами =)

2023-01-30 13:28 UTC, merged