Ansible 1
Otus-DevOps-22-08/morf100s_infra pull request #7
Opened 2023-01-16 16:44 UTC by morf100s

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Пересобран образ сервера app, так как отсутствовала утилита git
 - Даны ответ на вопрос из ДЗ
 - Описаны шаги для использования разных форматов INI

## Как запустить проект:
 - Равернуть инфраструктуру с помощью terraform
 - Получить ссылку на файл `terraform.tfstate` в s3
 - Запустить команду `ansible all -m ping`
 - Запустить команду `ansible-playbook clone.yml`

## Как проверить работоспособность:
 - Зайти по ssh на сервер и проверить наличие каталога `/home/ubuntu/reddit`
 - Проверить вывод команды ansible-playbook

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-01-17 12:15 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
К сожалению оооочень много ошибок, рекомендую свериться с результатами тестов
Большинство ошибок связаны с отступами и тд
Так же нужно починить терраформ
ДЗ возвращаю на доработку

2023-01-19 02:34 UTC, morf100s commented
Пофиксил что смог, остальное не ясно. Нужны Ваши комментарии.

1. Вывод явно говори, что тесты сломались. Команда `terraform validate -var-file` не отработает, так как `terraform` не имеет ключа `-var-file`:
```
     ×  Command: `cd terraform/prod && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example` stdout should match "Terraform has been successfully initialized!"
```

2. Неинформативная ошибка:
```
     +On ../modules/app/main.tf line 3: Unsuitable value: string required
```

2023-01-19 08:57 UTC, mrgreyves commented
Здравствуйте!)
https://developer.hashicorp.com/terraform/language/values/variables
![image](https://user-images.githubusercontent.com/34331259/213398370-82edf2fd-5bc0-49b7-938b-cb6c635faa21.png)
Да все он имеет =)

2023-01-19 09:54 UTC, morf100s commented
> Здравствуйте!) https://developer.hashicorp.com/terraform/language/values/variables ![image](https://user-images.githubusercontent.com/34331259/213398370-82edf2fd-5bc0-49b7-938b-cb6c635faa21.png) Да все он имеет =)

Так а причем здесь `terraform apply`? Да, `terraform apply` имеет ключ `-var-file=`, но в автотестах данный ключ применяется для `terraform validate`, а он не умеет и поэтому ошибка
```
cd terraform/stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example
```

2023-01-19 09:57 UTC, morf100s commented
Для наглядности, лог с моей машины:
```
[zcar@20sl stage]$ terraform apply -var-file="terraform.tfvars" | head

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.app.yandex_compute_instance.app will be created
  + resource "yandex_compute_instance" "app" {
      + created_at                = (known after apply)
[zcar@20sl stage]$ terraform validate -var-file="terraform.tfvars"
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -var-file
╵

For more help on using this command, run:
  terraform validate -help
[zcar@20sl stage]$ terraform -version
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/yandex-cloud/yandex v0.84.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
[zcar@20sl stage]$
```
Пожалуйста, исправьте автотесты, так как он просто не будут проходить.

2023-01-20 13:24 UTC, mrgreyves commented
Здравствуйте!)
У вас версия Terraform v1.3.5
И в этой версии в validate --var-file как директива удалена
Ранее она присутсвовала

2023-01-20 13:25 UTC, mrgreyves commented
Ошибка у вас в другом
В этом пр такие же проблемы
Кажется какая то проблема с секцией объявления провайдера
Я описывал эту проблемы в другом вашем пр

2023-01-20 13:26 UTC, mrgreyves commented
Версия которая используется в тестах Terraform v0.12.19
Там эта директива присутствует

2023-01-20 13:29 UTC, morf100s commented
> Ошибка у вас в другом В этом пр такие же проблемы Кажется какая то проблема с секцией объявления провайдера Я описывал эту проблемы в другом вашем пр

Хорошо. Вы можете мне сказать в чем проблема? Я по тестам не могу понять, мне неочевидно в чем дело.

2023-01-20 13:34 UTC, mrgreyves commented
![image](https://user-images.githubusercontent.com/34331259/213707027-f3e1192a-e17b-41e1-b022-93dd95191bad.png)
Закомментируйте эту секцию и перезапустите тест
Проверьте результат его работы

2023-01-20 16:27 UTC, mrgreyves commented
Получилось проверить у вас?)

2023-01-23 07:31 UTC, morf100s commented
Без этого блока не будут работать модули, так как terraform не поймет к какому провадеру они относятся.
Вот лог с моей машины:
```
[zcar@20sl prod]$ rm -fr .terraform .terraform.lock.hcl
[zcar@20sl prod]$ head -n 8 ../modules/app/main.tf
terraform {
  required_providers {
    yandex = {
      source = "yandex-cloud/yandex"
      version = "0.84.0"
    }
  }
}
[zcar@20sl prod]$ terraform init
Initializing modules...
- app in ../modules/app
- db in ../modules/db
- vpc in ../modules/vpc

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding yandex-cloud/yandex versions matching "0.84.0"...
- Installing yandex-cloud/yandex v0.84.0...
- Installed yandex-cloud/yandex v0.84.0 (self-signed, key ID E40F590B50BB8E40)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[zcar@20sl prod]$ 
[zcar@20sl prod]$ 
[zcar@20sl prod]$ rm -fr .terraform .terraform.lock.hcl
[zcar@20sl prod]$ head -n 8 ../modules/app/main.tf
#terraform {
#  required_providers {
#    yandex = {
#      source = "yandex-cloud/yandex"
#      version = "0.84.0"
#    }
#  }
#}
[zcar@20sl prod]$ terraform init
Initializing modules...
- app in ../modules/app
- db in ../modules/db
- vpc in ../modules/vpc

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding latest version of hashicorp/yandex...
- Finding yandex-cloud/yandex versions matching "0.84.0"...
- Installing yandex-cloud/yandex v0.84.0...
- Installed yandex-cloud/yandex v0.84.0 (self-signed, key ID E40F590B50BB8E40)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/yandex: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/yandex
│ 
│ Did you intend to use yandex-cloud/yandex? If so, you must specify that source address in each module which requires that provider. To see which modules are
│ currently depending on hashicorp/yandex, run the following command:
│     terraform providers
╵

[zcar@20sl prod]$ 
```

Пожалуйста, прокомментируйте или скорректируйте тесты с учетом методички ДЗ.

2023-01-23 19:33 UTC, mrgreyves commented
Здравствуйте!)
Подскажите, какую версию terraform вы используете на данный момент?
Так же предлагаю "не ломать" на данный момент тесты.

2023-01-24 04:04 UTC, morf100s commented
> Здравствуйте!) Подскажите, какую версию terraform вы используете на данный момент? Так же предлагаю "не ломать" на данный момент тесты.

Использую v1.3.5
```
[zcar@20sl ~]$ terraform -v
Terraform v1.3.5
on linux_amd64

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
[zcar@20sl ~]$ 
```

2023-01-24 09:57 UTC, morf100s commented
> Так же предлагаю "не ломать" на данный момент тесты.
Так никто их и не ломает, просто, они сейчас содержат ошибку, ее нужно исправить или исправить методичку, чтобы "идя" по ней состояние репы было таким чтобы тесты проходили.

2023-01-25 13:32 UTC, mrgreyves requested changes
Здравствуйте!)
Я вас понял, хорошо что вы используете актуальные версии приложений
ДЗ принимаю =)

2023-01-25 13:32 UTC, mrgreyves commented on terraform/modules/db/main.tf
> +terraform {
У вас вот сюда точно ничего не закралось странное?
Ошибка почему то появляется именно в этой секции

2023-01-25 13:32 UTC, mrgreyves commented on terraform/modules/db/main.tf
> +terraform {
Попробуйте различные варианты инициализации провайдера
Например удалите директиву определяющую версию провайдера

2023-01-25 13:33 UTC, mrgreyves approved these changes
Уууупс, и я нажал не ту кнопку =)

2023-01-30 13:37 UTC, merged